baseurl = "https://monba.dicook.org"
languageCode = "en-us"
title = "ETC3250: Business Analytics"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Textbook"
    url = "http://www-bcf.usc.edu/~gareth/ISL/"
    weight = 2
[[menu.main]]
    name = "Moodle (Marks, Ass't turn in, Discussion)"
    url = "https://lms.monash.edu/course/view.php?id=49079"
    weight = 3
[[menu.main]]
    name = "DataCamp"
    url = "https://www.datacamp.com"
    weight = 4
[[menu.main]]
    name = "Unit guide"
    url = "https://unitguidemanager.monash.edu/view?unitCode=ETC3250&tpCode=S1-01&tpYear=2019"
    weight = 5

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Di Cook](https://dicook.org) 2017-9 | [Github](https://github.com/dicook) | [Twitter](https://twitter.com/dicook)"
